export const START_PLAYING = 'START_PLAYING';
export const PAUSE_PLAYING = 'PAUSE_PLAYING';
export const SHOW_CONTROLS = 'SHOW_CONTROLS';
export const HIDE_CONTROLS = 'HIDE_CONTROLS';
export const SET_PLAYER_INFO = 'SET_PLAYER_INFO';
